## Default Kibana configuration from Kibana base image.
## https://github.com/elastic/kibana/blob/master/src/dev/build/tasks/os_packages/docker_generator/templates/kibana_yml.template.ts

# The Kibana server's name. This is used for display purpose.
server.name: kibana

# Kibana is served by a back end server. This specifies the port to use.
server.port: 5601

# The default is "localhost" which usually means remote machines will not be able to connect.
server.host: 0.0.0.0 
#server.host: "localhost"


# The URL's of the Elasticsearch instances to use for all your queries.
# This address is basically our container name is elasticsearch.
elasticsearch.hosts: ["http://elasticsearch:9200"]

monitoring.ui.container.elasticsearch.enabled: true


# If your Elastic server is protected with basic authentication, You need to 
# Enter the Elastic search credentials so then kibana can communicate with the elastic search.
## X-Pack security credentials
elasticsearch.username: elastic
elasticsearch.password: anypass
